tentativa/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genders
  resources :groups
  resources :users
  resources :habilities
  resources :clans
  resources :clan_members
  resources :main
  root 'main#index'
end

tentativa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tentativa/app/models/clan.rb
class Clan < ApplicationRecord
end

tentativa/app/models/clan_member.rb
class ClanMember < ApplicationRecord
  belongs_to :user
end

tentativa/app/models/gender.rb
class Gender < ApplicationRecord
end

tentativa/app/models/group.rb
class Group < ApplicationRecord
end

tentativa/app/models/hability.rb
class Hability < ApplicationRecord
end

tentativa/app/models/level.rb
class Level < ApplicationRecord
end

tentativa/app/models/store_item.rb
class StoreItem < ApplicationRecord
end

tentativa/app/models/sub_group.rb
class SubGroup < ApplicationRecord
  belongs_to :group
end

tentativa/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :taskClass
end

tentativa/app/models/task_class.rb
class TaskClass < ApplicationRecord
end

tentativa/app/models/task_participant.rb
class TaskParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :task
end

tentativa/app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

tentativa/app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  belongs_to :group
end

tentativa/app/models/user_hability.rb
class UserHability < ApplicationRecord
  belongs_to :user
  belongs_to :hability
end

tentativa/app/controllers/clan_members_controller.rb
class ClanMembersController < ApplicationController
	def index
		@cmbs = ClanMember.all
		@users = User.all
	end
	def new
		@cmbs = ClanMember.new()
		@clan = Clan.all.collect{|clan| [clan.name, clan.id]}
		@user = User.all.collect{|user| [user.name, user.id]}
	end
	def create
		@cmbs = ClanMember.new(cmbs_params)
		if @cmbs.save
			redirect_to clan_members_path
		else
			render 'new'
		end
	end
	def show
		@cmbs = ClanMember.find(params[:id])
		@userName = User.find(@cmbs.user_id).name
		@clanName = Clan.find(@cmbs.clan_id).name
	end
	def edit
		@cmbs = ClanMember.find(params[:id])
		@clan = Clan.all.collect{|clan| [clan.name, clan.id]}
		@user = User.all.collect{|user| [user.name, user.id]}
	end
	def update
		@cmbs = ClanMember.find(params[:id])
		if @cmbs.update(cmbs_params)
			redirect_to clan_members_path(params[:id])
		else
			render 'edit'
		end
	end
	def destroy
		@cmbs = ClanMember.find(params[:id])
		@cmbs.destroy
		redirect_to clan_members_path
	end

	private

	def cmbs_params
		params.require(:clan_member).permit(:user_id, :clan_id, :isLeager, :acceptedInvite)
	end
end

tentativa/app/helpers/clan_members_helper.rb
module ClanMembersHelper
end

tentativa/app/helpers/clans_helper.rb
module ClansHelper
end

tentativa/app/helpers/genders_helper.rb
module GendersHelper
end

tentativa/app/helpers/groups_helper.rb
module GroupsHelper
end

tentativa/app/helpers/habilities_helper.rb
module HabilitiesHelper
end

tentativa/app/helpers/main_helper.rb
module MainHelper
end

tentativa/app/helpers/users_helper.rb
module UsersHelper
end

tentativa/app/views/clan_members/edit.html.erb
<%= form_with scope: :clan_member, url: clan_member_path, method: :patch, local: true do |f|%>
	<%=f.label :user_id, 'Usuário'%><br/>
	<%=f.select :user_id, @user%><br/>
	<%=f.label :clan_id, 'Clan'%><br/>
	<%=f.select :clan_id, @clan%><br/>
	<%=f.label :isLeager, 'É lider do clan'%><br/>
	<%=f.check_box :isLeager%><br/>
	<%=f.label :acceptedInvite, 'Aceitou o convite'%><br/>
	<%=f.check_box :acceptedInvite%><br/>
	<%=f.submit 'Enviar', :class => "btn btn-success"%>
<%end%>

tentativa/app/views/clan_members/index.html.erb
<h2>Membros de Clans cadastrados:</h2>

<%@cmbs.each do |cmb|%>
	<%=@users.find(cmb.user_id).name%>
	<%=link_to 'Ver', clan_member_path(cmb.id), method: :get, :class => "btn btn-outline-primary"%><br/>
<%end%>
<br/>
<%=link_to 'Cadastrar novo membro de clan', new_clan_member_url, method: :get, :class => "btn btn-primary"%><br/>
<div style="padding: 10px 0;">
<%=link_to 'Voltar para a página principal', main_index_url, :class => "btn btn-primary"%>

tentativa/app/views/clan_members/new.html.erb
<%= form_with scope: :clan_member, url: clan_members_path, local: true do |f|%>
	<%=f.label :user_id, 'Usuário'%><br/>
	<%=f.select :user_id, @user%><br/>
	<%=f.label :clan_id, 'Clan'%><br/>
	<%=f.select :clan_id, @clan%><br/>
	<%=f.label :isLeager, 'É lider do clan'%><br/>
	<%=f.check_box :isLeager%><br/>
	<%=f.label :acceptedInvite, 'Aceitou o convite'%><br/>
	<%=f.check_box :acceptedInvite%><br/>
	<%=f.submit 'Enviar', :class => "btn btn-primary"%>
<%end%>

tentativa/app/views/clan_members/show.html.erb
<p>Dados do membro de clan:<p/><br/>
<p>Nome do usuário:<%=@userName%></p>
<p>id do usuário:<%=@cmbs.user_id%></p>
<p>Nome do clan:<%=@clanName%></p>
<p>id do clan:<%=@cmbs.clan_id%></p>
<p>é lider:<%=@cmbs.isLeager%></p>
<p>aceitou convite:<%=@cmbs.acceptedInvite%></p>

<%=link_to 'Editar membro de clan', edit_clan_member_url(@cmbs.id), method: :get, :class => "btn btn-primary"%>
<%=link_to 'Apagar membro de clan', clan_member_path(@cmbs.id), method: :delete,  :class => "btn btn-danger"%><br/>
<%=link_to 'Voltar', users_path,  :class => "btn btn-primary"%>