tentativa/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genders
  resources :groups
  resources :users
  resources :habilities
  resources :clans
  resources :clan_members
  resources :main
  root 'main#index'
end

tentativa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tentativa/app/models/clan.rb
class Clan < ApplicationRecord
end

tentativa/app/models/clan_member.rb
class ClanMember < ApplicationRecord
  belongs_to :user
end

tentativa/app/models/gender.rb
class Gender < ApplicationRecord
end

tentativa/app/models/group.rb
class Group < ApplicationRecord
end

tentativa/app/models/hability.rb
class Hability < ApplicationRecord
end

tentativa/app/models/level.rb
class Level < ApplicationRecord
end

tentativa/app/models/store_item.rb
class StoreItem < ApplicationRecord
end

tentativa/app/models/sub_group.rb
class SubGroup < ApplicationRecord
  belongs_to :group
end

tentativa/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :taskClass
end

tentativa/app/models/task_class.rb
class TaskClass < ApplicationRecord
end

tentativa/app/models/task_participant.rb
class TaskParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :task
end

tentativa/app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

tentativa/app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  belongs_to :group
end

tentativa/app/models/user_hability.rb
class UserHability < ApplicationRecord
  belongs_to :user
  belongs_to :hability
end

tentativa/app/controllers/clans_controller.rb
class ClansController < ApplicationController
	def index
		@clans = Clan.all
	end
	def new
		@clan = Clan.new()
	end
	def create
		@clan = Clan.new(clan_params)
		if @clan.save
			redirect_to clans_path
		else
			render 'new'
		end
	end
	def show
		@clan = Clan.find(params[:id])
	end
	def edit
		@clan = Clan.find(params[:id])
	end
	def update
		@clan = Clan.find(params[:id])
		if @clan.update(clan_params)
			redirect_to clan_path(params[:id])
		else
			render 'edit'
		end
	end
	def destroy
		@clan = Clan.find(params[:id])
		@clan.destroy
		redirect_to clans_path
	end

	private

	def clan_params
		params.require(:clan).permit(:name, :deadline)
	end
end

tentativa/app/helpers/application_helper.rb
module ApplicationHelper
end

tentativa/app/helpers/clans_helper.rb
module ClansHelper
end

tentativa/app/helpers/genders_helper.rb
module GendersHelper
end

tentativa/app/helpers/groups_helper.rb
module GroupsHelper
end

tentativa/app/helpers/habilities_helper.rb
module HabilitiesHelper
end

tentativa/app/helpers/main_helper.rb
module MainHelper
end

tentativa/app/helpers/users_helper.rb
module UsersHelper
end

tentativa/app/views/clans/edit.html.erb
<%= form_with scope: :clan, url: clan_path, method: :patch, local: true do |f|%>
	<%=f.label :name, 'Nome'%><br/>
	<%=f.text_field :name%><br/>
	<%=f.label :deadline, 'Data de expiração'%><br/>
	<%=f.date_field :deadline%><br/>
	<%=f.submit 'Enviar', :class => "btn btn-primary"%>
<%end%>

tentativa/app/views/clans/index.html.erb
<p>Clans cadastrados:</p>

<%@clans.each do |clan|%>
	<%=clan.name%>
	<%=link_to 'Ver', clan_path(clan.id), method: :get, :class => "btn btn-outline-primary"%><br/>
<%end%>
<br/>
<%=link_to 'Cadastrar novo clan', new_clan_url, method: :get, :class => "btn btn-primary"%><br/>
<div style="padding: 10px 0;">
<%=link_to 'Voltar para a página principal', main_index_url, :class => "btn btn-primary"%>

tentativa/app/views/clans/new.html.erb
<%= form_with scope: :clan, url: clans_path, local: true do |f|%>
	<%=f.label :name, 'Nome'%><br/>
	<%=f.text_field :name%><br/>
	<%=f.label :deadline, 'Data de expiração'%><br/>
	<%=f.date_field :deadline%><br/>
	<%=f.submit 'Enviar',  :class => "btn btn-success"%>
<%end%>

tentativa/app/views/clans/show.html.erb
<p>Dados do clan:<p/><br/>
<p>Nome:<%=@clan.name%></p>
<p>Data de expiração:<%=@clan.deadline%></p>

<%=link_to 'Editar clan', edit_clan_url(@clan.id), method: :get, :class => "btn btn-primary"%>
<%=link_to 'Apagar clan', clan_path(@clan.id), method: :delete,  :class => "btn btn-danger"%><br/>
<%=link_to 'Voltar', users_path,  :class => "btn btn-primary"%>