tentativa/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genders
  resources :groups
  resources :users
  resources :habilities
  resources :clans
  resources :clan_members
  resources :main
  root 'main#index'
end

tentativa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tentativa/app/models/clan.rb
class Clan < ApplicationRecord
end

tentativa/app/models/clan_member.rb
class ClanMember < ApplicationRecord
  belongs_to :user
end

tentativa/app/models/gender.rb
class Gender < ApplicationRecord
end

tentativa/app/models/group.rb
class Group < ApplicationRecord
end

tentativa/app/models/hability.rb
class Hability < ApplicationRecord
end

tentativa/app/models/level.rb
class Level < ApplicationRecord
end

tentativa/app/models/store_item.rb
class StoreItem < ApplicationRecord
end

tentativa/app/models/sub_group.rb
class SubGroup < ApplicationRecord
  belongs_to :group
end

tentativa/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :taskClass
end

tentativa/app/models/task_class.rb
class TaskClass < ApplicationRecord
end

tentativa/app/models/task_participant.rb
class TaskParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :task
end

tentativa/app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

tentativa/app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  belongs_to :group
end

tentativa/app/models/user_hability.rb
class UserHability < ApplicationRecord
  belongs_to :user
  belongs_to :hability
end

tentativa/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
	end
	def new
		@group = Group.new()
	end
	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to groups_path
		else
			render 'new'
		end
	end
	def edit
		@group = Group.find(params[:id])
	end
	def update
		@group = Group.find(params[:id])
		if @group.update(group_params)
			redirect_to groups_path
		else
			render 'edit'
		end
	end
	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end

	private

	def group_params
		params.require(:group).permit(:name)
	end
end

tentativa/app/helpers/application_helper.rb
module ApplicationHelper
end

tentativa/app/helpers/clans_helper.rb
module ClansHelper
end

tentativa/app/helpers/genders_helper.rb
module GendersHelper
end

tentativa/app/helpers/groups_helper.rb
module GroupsHelper
end

tentativa/app/helpers/habilities_helper.rb
module HabilitiesHelper
end

tentativa/app/helpers/main_helper.rb
module MainHelper
end

tentativa/app/helpers/users_helper.rb
module UsersHelper
end

tentativa/app/views/groups/edit.html.erb
<%=form_with scope: :group, url: group_path(@group.id), method: :patch, local: true do |f|%>
	<%=f.label :name, 'Nome do grupo'%><br/>
	<%=f.text_field :name%><br/>
	<%=f.submit 'Enviar', :class =>"btn btn-success"%>
<%end%>

tentativa/app/views/groups/index.html.erb
<p>Grupos cadastrados:</p>

<%@groups.each do |group|%>
	<%=group.name%>
	<%=link_to 'Apagar', group_path(group.id), method: :delete, :class =>"btn btn-danger"%>
	<%=link_to 'Editar', edit_group_url(group.id), :class =>"btn btn-primary"%><br/>
<%end%>
<br/>
<%=link_to 'Cadastrar novo grupo', new_group_url, method: :get, :class =>"btn btn-primary"%><br/>
<div style="padding: 10px 0;">
<%=link_to 'Voltar para a página principal', main_index_url, :class =>"btn btn-primary"%>

tentativa/app/views/groups/new.html.erb
<%=form_with scope: :group, url: groups_path, local: true do |f|%>
	<%= f.label :name, 'Nome do grupo'%><br/>
	<%= f.text_field :name%><br/>
	<%=f.submit 'Enviar', :class =>"btn btn-success"%>
<%end%>