tentativa/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :genders
  resources :groups
  resources :users
  resources :habilities
  resources :clans
  resources :clan_members
  resources :main
  root 'main#index'
end

tentativa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tentativa/app/models/clan.rb
class Clan < ApplicationRecord
end

tentativa/app/models/clan_member.rb
class ClanMember < ApplicationRecord
  belongs_to :user
end

tentativa/app/models/gender.rb
class Gender < ApplicationRecord
end

tentativa/app/models/group.rb
class Group < ApplicationRecord
end

tentativa/app/models/hability.rb
class Hability < ApplicationRecord
end

tentativa/app/models/level.rb
class Level < ApplicationRecord
end

tentativa/app/models/store_item.rb
class StoreItem < ApplicationRecord
end

tentativa/app/models/sub_group.rb
class SubGroup < ApplicationRecord
  belongs_to :group
end

tentativa/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :taskClass
end

tentativa/app/models/task_class.rb
class TaskClass < ApplicationRecord
end

tentativa/app/models/task_participant.rb
class TaskParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :task
end

tentativa/app/models/task_status.rb
class TaskStatus < ApplicationRecord
end

tentativa/app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  belongs_to :group
end

tentativa/app/models/user_hability.rb
class UserHability < ApplicationRecord
  belongs_to :user
  belongs_to :hability
end

tentativa/app/controllers/main_controller.rb
class MainController < ApplicationController
end

tentativa/app/helpers/clans_helper.rb
module ClansHelper
end

tentativa/app/helpers/genders_helper.rb
module GendersHelper
end

tentativa/app/helpers/groups_helper.rb
module GroupsHelper
end

tentativa/app/helpers/habilities_helper.rb
module HabilitiesHelper
end

tentativa/app/helpers/main_helper.rb
module MainHelper
end

tentativa/app/helpers/users_helper.rb
module UsersHelper
end

tentativa/app/views/main/index.html.erb
<h1 class="text-center">Página inicial</h1>

<div class="container" style="padding-top: 100px;">
    <div class="row">
        <div class="col-2">
            <%=link_to 'Usuários', users_path, :class => 'btn btn-primary'%><br/>
        </div>
        <div class="col-2">
            <%=link_to 'Grupos', groups_path, :class => 'btn btn-primary'%><br/>
        </div>
        <div class="col-2">
            <%=link_to 'Generos', genders_path, :class => 'btn btn-primary'%><br/>
        </div>
        <div class="col-2">
            <%=link_to 'Habilidades', habilities_path, :class => 'btn btn-primary'%><br/>
        </div>
        <div class="col-2">
            <%=link_to 'Clans', clans_path, :class => 'btn btn-primary'%><br/>
        </div>
        <div class="col-2">
            <%=link_to 'Membors de clans', clan_members_path, :class => 'btn btn-primary'%><br/>
        </div>
</div>